server:
  port: 8081

spring:
  application:
    name: gateway-service
  main:
    banner-mode: console # Disable the Spring logo
  #        web-application-type: none
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: mongodb+srv://quangnam130520:Z72BGxu7D8VmvHKq@cluster0.fwoaemp.mongodb.net/?retryWrites=true&w=majority
      database: football

  datasource:
    url: jdbc:mysql://localhost:3306/gateway?allowpublickeyretrieval=true&usessl=false
    username: root
    password: A%9jr>NK
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

  sql:
    init:
      platform: mysql
      mode: always

  redis:
    host: localhost
    port: 6379
    client-name: redis
#    password: 123456
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1
#        enabled: true
#    lettuce:
#      pool:
#        max-wait: -1




# API Gateway Configuration
api-gateway:
    service-1:
        host: localhost
        port: 8080
    mappings:
        "[/api/**]" : ${api-gateway.service-1.host}:${api-gateway.service-1.port}
#        "[/swagger-ui/**]": ${api-gateway.host}:${api-gateway.port}

auth:
  users:
    loginadmin:
      role: admin
      password: loginpass
    bookadmin:
      role: USER
      password: bookpass