server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    banner-mode: console # Disable the Spring logo
  #        web-application-type: none
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: mongodb+srv://quangnam130520:Z72BGxu7D8VmvHKq@cluster0.fwoaemp.mongodb.net/?retryWrites=true&w=majority
      database: football

  datasource:
    url: jdbc:mysql://localhost:3306/gateway?allowpublickeyretrieval=true&usessl=false
    username: root
    password: A%9jr>NK
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

# Redis Configuration
  redis:
    host: localhost
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 10
        time-between-eviction-runs: 10000
        max-wait: 10000
    user_expiration_second: 2400
    access_token_expiration_second: 1800
    refresh_token_expiration_second: 3600
    activate_token_expiration_second: 86400
    default_expiration_second: 1200


  sql:
    init:
      platform: mysql
      mode: always



  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com/
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
      client:
        registration:
          google:
            clientId: 773619103626-c457k0qqgip96ej65846p61j6ij47fcs.apps.googleusercontent.com
            clientSecret: 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
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-authentication-method: basic
#            provider: google
            scope:
              - openid  #if add, loadUser will not execute
              - profile
              - email
#              - https://www.googleapis.com/auth/userinfo.email
#              - https://www.googleapis.com/auth/userinfo.profile
#              - openid
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: Google


# API Gateway Configuration
api-gateway:
    service-1:
        host: localhost
        port: 8080
    mappings:
        "[/api/**]" : ${api-gateway.service-1.host}:${api-gateway.service-1.port}
#        "[/swagger-ui/**]": ${api-gateway.host}:${api-gateway.port}


santos:
    jwt:
        secret: 4261656C64756E67.4261656C64756E67
        access_token_expiration_second: 1800 # 30 minutes
        refresh_token_expiration_second: 3600


