package org.authen.service.authen;

import org.authen.model.dto.login.LoginRequestDTO;
import org.authen.model.dto.register.RegisterDTO;
import org.authen.model.dto.logout.LogoutRequestDTO;
import org.authen.exception.apiEx.ResponseModel;
import org.springframework.http.ResponseEntity;

public interface AuthenticationService {
	ResponseEntity<ResponseModel> registerAccount(RegisterDTO request);
	ResponseEntity<ResponseModel> autoGeneratedPassword();
	ResponseEntity<ResponseModel> login(LoginRequestDTO request);
	ResponseEntity<ResponseModel> logout(LogoutRequestDTO request);
}
