package org.authen.service.authen;

import org.authen.dto.login.LoginRequestDTO;
import org.authen.dto.register.RegisterDTORequest;
import org.authen.dto.logout.LogoutRequestDTO;
import org.authen.exception.apiEx.ResponseModel;
import org.springframework.http.ResponseEntity;

import javax.servlet.http.HttpServletRequest;

public interface AuthenticationService {
	ResponseEntity<ResponseModel> registerAccount(RegisterDTORequest registerDTORequest, HttpServletRequest request);
	ResponseEntity<ResponseModel> autoGeneratedPassword();
	ResponseEntity<ResponseModel> login(LoginRequestDTO request);
	ResponseEntity<ResponseModel> logout(LogoutRequestDTO request);
	ResponseEntity<ResponseModel> confirmRegistration(String token, HttpServletRequest request);
}
