package org.gateway.auth.service;

import org.gateway.auth.model.dto.login.LoginRequestDTO;
import org.gateway.auth.model.dto.register.RegisterDTO;
import org.gateway.auth.model.dto.logout.LogoutRequestDTO;
import org.gateway.common.exception.apiEx.ResponseModel;
import org.springframework.http.ResponseEntity;

public interface AuthenticationService {
	ResponseEntity<ResponseModel> registerAccount(RegisterDTO request);
	ResponseEntity<ResponseModel> autoGeneratedPassword();
	ResponseEntity<ResponseModel> login(LoginRequestDTO request);
	ResponseEntity<ResponseModel> logout(LogoutRequestDTO request);
}
